import type {
  AnimationConfig,
  BackgroundSettings,
  GridSettings,
  MasterSlide,
  PresentationProject,
  ShapeElement,
  Slide,
  NotesBoard,
  TextElement,
  WorkspaceConfig,
} from "./types";
import { APP_VERSION, newId } from "./utils";
import { defaultContextMenuItems } from "./contextMenuRegistry";

export const defaultAnimation = (): AnimationConfig => ({
  kind: "none",
  trigger: "with-slide",
  duration: 0.6,
  delay: 0,
});

export const defaultGrid = (): GridSettings => ({
  enabled: false,
  columns: 12,
  gutter: 24,
  marginX: 96,
  marginY: 72,
  baseline: 12,
});

export const defaultBackground = (inherit = true): BackgroundSettings => ({
  inherit,
  color: "#f4f2ec",
  type: "color",
  fit: "cover",
});

function welcomeElements(): Array<TextElement | ShapeElement> {
  const accent: ShapeElement = {
    id: newId("shape"),
    type: "shape",
    shape: "rect",
    name: "Kiemelő vonal",
    x: 128,
    y: 151,
    width: 112,
    height: 12,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    fill: "#ff6b45",
    fillType: "color",
    fillFit: "cover",
    gradientFrom: "#ff6b45",
    gradientTo: "#ffb36b",
    gradientAngle: 0,
    fillPosterTime: 0,
    stroke: "transparent",
    strokeWidth: 0,
    radius: 6,
    animation: defaultAnimation(),
  };
  const title: TextElement = {
    id: newId("text"),
    type: "text",
    name: "Főcím",
    x: 128,
    y: 212,
    width: 1240,
    height: 250,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    text: "Pre'on",
    dynamicField: "none",
    numberFormat: "1",
    dynamicPrefix: "",
    dynamicSuffix: "",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 150,
    fontWeight: 720,
    fontStyle: "normal",
    textDecoration: "none",
    strikethrough: false,
    textTransform: "none",
    fontVariantCaps: "normal",
    baselineMode: "normal",
    baselineShift: 0,
    ligatures: true,
    paragraphSpacingBefore: 0,
    paragraphSpacingAfter: 0,
    firstLineIndent: 0,
    lineHeight: 0.9,
    lineHeightAuto: false,
    letterSpacing: -5,
    letterSpacingAuto: false,
    color: "#17181b",
    textAlign: "left",
    verticalAlign: "top",
    background: "transparent",
    padding: 0,
    resizeMode: "box",
    animation: { kind: "fade-up", trigger: "with-slide", duration: 0.8, delay: 0.1 },
  };
  const subtitle: TextElement = {
    id: newId("text"),
    type: "text",
    name: "Alcím",
    x: 136,
    y: 746,
    width: 890,
    height: 110,
    rotation: 0,
    opacity: 0.78,
    visible: true,
    locked: false,
    text: "Precíz prezentációs layout, videó, élő webtartalom és hordozható HTML egy helyen.",
    dynamicField: "none",
    numberFormat: "1",
    dynamicPrefix: "",
    dynamicSuffix: "",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 34,
    fontWeight: 430,
    fontStyle: "normal",
    textDecoration: "none",
    strikethrough: false,
    textTransform: "none",
    fontVariantCaps: "normal",
    baselineMode: "normal",
    baselineShift: 0,
    ligatures: true,
    paragraphSpacingBefore: 0,
    paragraphSpacingAfter: 0,
    firstLineIndent: 0,
    lineHeight: 1.25,
    lineHeightAuto: false,
    letterSpacing: 0,
    letterSpacingAuto: false,
    color: "#17181b",
    textAlign: "left",
    verticalAlign: "top",
    background: "transparent",
    padding: 0,
    resizeMode: "box",
    animation: { kind: "fade", trigger: "with-slide", duration: 0.7, delay: 0.35 },
  };
  const hint: TextElement = {
    id: newId("text"),
    type: "text",
    name: "Tipp",
    x: 1430,
    y: 824,
    width: 340,
    height: 90,
    rotation: 0,
    opacity: 0.56,
    visible: true,
    locked: false,
    text: "Tipp: húzz segédvonalat a vonalzóról, majd mozgasd az elemeket.",
    dynamicField: "none",
    numberFormat: "1",
    dynamicPrefix: "",
    dynamicSuffix: "",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 24,
    fontWeight: 450,
    fontStyle: "normal",
    textDecoration: "none",
    strikethrough: false,
    textTransform: "none",
    fontVariantCaps: "normal",
    baselineMode: "normal",
    baselineShift: 0,
    ligatures: true,
    paragraphSpacingBefore: 0,
    paragraphSpacingAfter: 0,
    firstLineIndent: 0,
    lineHeight: 1.35,
    lineHeightAuto: false,
    letterSpacing: 0,
    letterSpacingAuto: false,
    color: "#17181b",
    textAlign: "left",
    verticalAlign: "top",
    background: "transparent",
    padding: 0,
    resizeMode: "box",
    animation: defaultAnimation(),
  };
  return [accent, title, subtitle, hint];
}


export function defaultNotesTextElement(): TextElement {
  return {
    id: newId("text"),
    type: "text",
    name: "Előadói jegyzet",
    x: 72,
    y: 72,
    width: 756,
    height: 1056,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    text: "",
    dynamicField: "none",
    numberFormat: "1",
    dynamicPrefix: "",
    dynamicSuffix: "",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 38,
    fontWeight: 400,
    fontStyle: "normal",
    textDecoration: "none",
    strikethrough: false,
    textTransform: "none",
    fontVariantCaps: "normal",
    baselineMode: "normal",
    baselineShift: 0,
    ligatures: true,
    paragraphSpacingBefore: 0,
    paragraphSpacingAfter: 0,
    firstLineIndent: 0,
    lineHeight: 1.25,
    lineHeightAuto: false,
    letterSpacing: 0,
    letterSpacingAuto: true,
    color: "#202226",
    textAlign: "left",
    verticalAlign: "top",
    background: "transparent",
    padding: 0,
    resizeMode: "box",
    animation: defaultAnimation(),
  };
}

export function defaultNotesBoard(): NotesBoard {
  return {
    name: "Előadói jegyzet",
    mode: "text",
    // Portrait 3:4 by default so the note reads immediately as a note card, not a second slide.
    width: 900,
    height: 1200,
    background: { ...defaultBackground(false), color: "#e9efe6" },
    guides: { vertical: [], horizontal: [] },
    grid: { ...defaultGrid(), enabled: false },
    // Kept as a ready-to-use visual-note starter. Text mode uses Slide.notes instead.
    elements: [defaultNotesTextElement()],
  };
}

export function createDefaultProject(): PresentationProject {
  const now = new Date().toISOString();
  const masterId = newId("master");
  const master: MasterSlide = {
    id: masterId,
    name: "Alap mester",
    parentMasterId: null,
    inheritParentGrid: false,
    background: { ...defaultBackground(false), color: "#f4f2ec" },
    guides: { vertical: [96, 1824], horizontal: [72, 1008] },
    grid: defaultGrid(),
    elements: [],
  };
  const slide: Slide = {
    id: newId("slide"),
    name: "Nyitó oldal",
    hidden: false,
    masterId,
    background: defaultBackground(true),
    guides: { vertical: [], horizontal: [] },
    grid: defaultGrid(),
    inheritMasterGrid: true,
    elements: welcomeElements(),
    notes: "",
    notesBoard: defaultNotesBoard(),
    transition: "fade",
    longformHeightScale: 1,
    longformSticky: false,
  };
  return {
    format: "presentation-studio",
    formatVersion: 1,
    appVersion: APP_VERSION,
    id: newId("project"),
    name: "Új prezentáció",
    width: 1920,
    height: 1080,
    presentationMode: "slides",
    htmlExportMode: "standard",
    slides: [slide],
    sections: [],
    masters: [master],
    assets: [],
    textStyles: [],
    createdAt: now,
    updatedAt: now,
  };
}

export const defaultWorkspace: WorkspaceConfig = {
  name: "Presentation",
  leftVisible: true,
  rightVisible: true,
  leftWidth: 248,
  rightWidth: 328,
  leftTab: "slides",
  rightTab: "properties",
  showRulers: true,
  showGuides: true,
  showGrid: false,
  smartGuides: true,
  snapEnabled: true,
  theme: "dark",
  darkBrightness: 50,
  lightBrightness: 50,
  language: "hu",
  canvasView: "single",
  trimView: false,
  showNotesBoard: false,
  recentFonts: [],
  favoriteFonts: [],
  selectedShape: "rect",
  contextMenuItems: defaultContextMenuItems,
  toolbarItems: [
    "select",
    "hand",
    "text",
    "shape",
    "imageFrame",
    "image",
    "slideshow",
    "video",
    "model3d",
    "web",
    "separator",
    "undo",
    "redo",
    "duplicate",
    "delete",
    "separator",
    "align",
    "group",
  ],
};
