import { defaultAnimation } from "./defaultProject";
import type {
  ImageElement,
  SlideshowElement,
  PdfElement,
  ShapeElement,
  ShapeKind,
  TextElement,
  VideoElement,
  WebElement,
  Model3DElement,
} from "./types";
import { newId } from "./utils";

export function createTextElement(x = 160, y = 160): TextElement {
  return {
    id: newId("text"),
    type: "text",
    name: "Szöveg",
    x,
    y,
    width: 620,
    height: 140,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    text: "Új szöveg",
    dynamicField: "none",
    numberFormat: "1",
    dynamicPrefix: "",
    dynamicSuffix: "",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 64,
    fontWeight: 600,
    fontStyle: "normal",
    textDecoration: "none",
    strikethrough: false,
    textTransform: "none",
    fontVariantCaps: "normal",
    baselineMode: "normal",
    baselineShift: 0,
    ligatures: true,
    paragraphSpacingBefore: 0,
    paragraphSpacingAfter: 0,
    firstLineIndent: 0,
    lineHeight: 1.05,
    lineHeightAuto: true,
    letterSpacing: -1,
    letterSpacingAuto: true,
    color: "#17181b",
    textAlign: "left",
    verticalAlign: "top",
    background: "transparent",
    padding: 0,
    resizeMode: "box",
    animation: defaultAnimation(),
  };
}

export function createShapeElement(kind: ShapeKind, x = 240, y = 240): ShapeElement {
  const isLine = kind === "line";
  const names: Record<ShapeKind, string> = {
    rect: "Téglalap",
    "rounded-rect": "Lekerekített téglalap",
    ellipse: "Ellipszis",
    triangle: "Háromszög",
    star: "Csillag",
    polygon: "Sokszög",
    line: "Vonal",
    arrow: "Nyíl",
  };
  return {
    id: newId("shape"),
    type: "shape",
    shape: kind,
    name: names[kind],
    x,
    y,
    width: isLine ? 420 : 360,
    height: isLine ? 4 : (kind === "arrow" ? 180 : 240),
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    fill: isLine ? "#17181b" : "#ff6b45",
    fillType: "color",
    fillFit: "cover",
    gradientFrom: "#ff6b45",
    gradientTo: "#ffb36b",
    gradientAngle: 0,
    fillPosterTime: 0,
    stroke: "transparent",
    strokeWidth: 0,
    radius: kind === "rounded-rect" ? 48 : kind === "rect" ? 0 : 0,
    animation: defaultAnimation(),
  };
}

export function createImageElement(assetId: string, x = 240, y = 200): ImageElement {
  return {
    id: newId("image"),
    type: "image",
    name: "Kép",
    x,
    y,
    width: 720,
    height: 480,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    assetId,
    fit: "cover",
    radius: 12,
    borderColor: "transparent",
    borderWidth: 0,
    contentPositionX: 50,
    contentPositionY: 50,
    contentScale: 1,
    mask: { kind: "none" },
    animation: defaultAnimation(),
  };
}

export function createSlideshowElement(assetIds: string[] = [], x = 240, y = 180): SlideshowElement {
  return {
    id: newId("slideshow"),
    type: "slideshow",
    name: "Slideshow",
    x,
    y,
    width: 720,
    height: 480,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    assetIds: [...assetIds],
    fit: "cover",
    radius: 12,
    borderColor: "transparent",
    borderWidth: 0,
    contentPositionX: 50,
    contentPositionY: 50,
    contentScale: 1,
    mask: { kind: "none" },
    interval: 3,
    transition: "fade",
    transitionDuration: 0.6,
    startMode: "slide-enter",
    loop: true,
    clickToggle: true,
    animation: defaultAnimation(),
  };
}

export function createPdfElement(assetId: string, pageCount = 1, x = 240, y = 120): PdfElement {
  return {
    id: newId("pdf"),
    type: "pdf",
    name: "PDF oldal",
    x,
    y,
    width: 720,
    height: 960,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    assetId,
    page: 1,
    pageCount: Math.max(1, pageCount),
    fit: "contain",
    radius: 0,
    borderColor: "transparent",
    borderWidth: 0,
    contentPositionX: 50,
    contentPositionY: 50,
    contentScale: 1,
    mask: { kind: "none" },
    animation: defaultAnimation(),
  };
}

export function createVideoElement(assetId: string, x = 240, y = 200): VideoElement {
  return {
    id: newId("video"),
    type: "video",
    name: "Videó",
    x,
    y,
    width: 960,
    height: 540,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    assetId,
    fit: "cover",
    radius: 12,
    autoplay: true,
    loop: true,
    muted: true,
    controls: false,
    startTime: 0,
    posterTime: 0,
    mask: { kind: "none" },
    animation: defaultAnimation(),
  };
}

export function createWebElement(url = "https://example.com", x = 200, y = 150): WebElement {
  return {
    id: newId("web"),
    type: "web",
    name: "Web beágyazás",
    x,
    y,
    width: 1100,
    height: 680,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    sourceType: "url",
    url,
    radius: 12,
    interactiveInEditor: false,
    animation: defaultAnimation(),
  };
}


export function createModel3DElement(assetId: string, x = 260, y = 180): Model3DElement {
  return {
    id: newId("model3d"),
    type: "model3d",
    name: "3D modell",
    x,
    y,
    width: 820,
    height: 620,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    assetId,
    interaction: "orbit",
    autoRotate: false,
    autoRotateSpeed: 20,
    orbitTheta: 0,
    orbitPhi: 75,
    fieldOfView: 30,
    cameraDistance: 100,
    parallaxStrength: 16,
    scrollRotation: 180,
    exposure: 1,
    shadowIntensity: 1,
    backgroundColor: "#f4f2ec",
    transparentBackground: true,
    interactiveInEditor: false,
    animation: defaultAnimation(),
  };
}
